name: Build-Debug

on:
  push:
    branches:
      - "master"
  pull_request:
    branches:
      - "master"

jobs:
  build-unity:
    strategy:
      matrix:
        unity: ["2022.3.5f1"]
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v3
      - name: Build (Linux64, mono)
      
        uses: Cysharp/Actions/.github/actions/unity-builder@main
        env:
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
        with:
          unityVersion: ${{ matrix.unity }}
          targetPlatform: StandaloneLinux64
          customParameters: /headless /ScriptBackend mono
          
      - uses: actions/upload-artifact@v2
        with:
          name: my-artifacts
          path: ./Assets
